version: '3'

services:

  php:
    image: webdevops/php-nginx:8.0-alpine
    environment:
      WEB_DOCUMENT_ROOT: /var/www/dist
      WEB_DOCUMENT_INDEX: index.html
    working_dir: /var/www
    ports:
      - "${HTTP_PORT}:80"
    volumes:
      - ./:/var/www
      - ./10-php.conf:/opt/docker/etc/nginx/vhost.common.d/10-php.conf
